NO_TEXT_ERROR_MSG = 'Пришли текстовое сообщение.'
NO_PHOTO_MSG = 'Пожалуйста, отправь только фото растения.'
NO_DAYS_SELECTED_MSG = 'Выбери хотя бы один день!'
DATE_BAD_FORMAT = (
    '❌ Неверный формат даты. Используй формат ДД-ММ, например 15-04.'
)
DATE_BAD_DAY_RANGE = '❌ День должен быть от 1 до 31.'
DATE_BAD_MONTH_RANGE = '❌ Месяца {month} не существует.'
DATE_INVALID_DAY_IN_MONTH = '❌ В месяце {month} нет дня {day}.'
NO_POSITIVE_INT_MSG = 'Введи положительное число.'
NO_USER_MSG = 'Ошибка: не удалось определить пользователя.'
NOT_REGISTERED_MSG = 'Вы не зарегистрированы.'
UNDEFINED_TYPE_ERROR = 'Неизвестный тип удобрения'
NO_SCHEDULE_ERROR = 'Расписание не задано'
NO_DAYS_ERROR = 'Дни не указаны.'
UNDEFINED_SCHEDULE_TYPE_ERROR = 'Неизвестный тип расписания: {type}'
NO_PLANTS_MSG = 'Растений нет'
WRONG_FSM_CLASS_ERROR = 'FSM class "{class_name}" not found'
SKIP_ACTION_ERROR_MSG = 'Ошибка при возврате'
